### ISSUE TITLE
kitchen failed "The requested URL returned error: 404 Not Found"

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/ansible-role-root#7]
https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2-x86_64_chef-provisionerless.box does not exist.

**Comment by mitsururike** [comment]
URL has been changed to https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box

**Comment by trombik** [comment]
VM images from opscode should not be used because we should not rely on external images. See a list of official images at https://github.com/reallyenglish/ansible-role-example/wiki/Pitfalls#tests-on-jenkins-is-slow

**Comment by mitsururike** [comment]
how to reproduce:
 vagrant box remove trombik/ansible-centos-7.2-x86_64
 bundle exec kitchen test

it is an issue of kitchen-vagrant. upgrading it to 0.20 solves the problem.

**Comment by trombik** [comment]
`reallyenglish/ansible-role-*` is not supposed to work with _plain_ box images, or third-party images.

https://github.com/kaorimatz/packer-templates/compare/master...reallyenglish:reallyenglish-master

these modifications are added to make `kitchen` faster.

**Comment by trombik** [comment]
if you are going to update `Gemfile`, make sure to create patches for `ansible-role-qa` and `ansible-role-init`.
